import fs from 'node:fs';
import path from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import pg from 'pg';
import { config } from './config.ts';

type SqlParams = Array<string | number | null | bigint>;

export interface DbAdapter {
  exec(sql: string): Promise<void>;
  run(sql: string, params?: SqlParams): Promise<void>;
  get<T = Record<string, unknown>>(sql: string, params?: SqlParams): Promise<T | undefined>;
  all<T = Record<string, unknown>>(sql: string, params?: SqlParams): Promise<T[]>;
  close(): Promise<void>;
  kind: string;
}

const SQLITE_SCHEMA = `
CREATE TABLE IF NOT EXISTS orgs (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  full_name TEXT,
  role TEXT NOT NULL,
  permissions TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  failed_login_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until TEXT,
  last_login TEXT,
  totp_secret TEXT,
  totp_enabled INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(org_id, username)
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  ip_address TEXT,
  user_agent TEXT,
  last_activity TEXT
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY,
  org_id TEXT,
  user_id TEXT,
  action TEXT NOT NULL,
  description TEXT,
  details TEXT,
  ip_address TEXT,
  user_agent TEXT,
  timestamp TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS metrics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  org_id TEXT,
  name TEXT NOT NULL,
  value REAL NOT NULL,
  unit TEXT,
  source TEXT,
  category TEXT,
  tags TEXT,
  timestamp TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_metrics_name_ts ON metrics(name, timestamp);
CREATE INDEX IF NOT EXISTS idx_metrics_source_ts ON metrics(source, timestamp);
CREATE INDEX IF NOT EXISTS idx_metrics_org_ts ON metrics(org_id, timestamp);

CREATE TABLE IF NOT EXISTS alerts (
  id TEXT PRIMARY KEY,
  org_id TEXT,
  rule_id TEXT,
  name TEXT,
  description TEXT,
  severity TEXT,
  status TEXT,
  source TEXT,
  timestamp TEXT,
  acknowledged_at TEXT,
  resolved_at TEXT,
  acknowledged_by TEXT,
  resolved_by TEXT,
  metadata TEXT
);

CREATE TABLE IF NOT EXISTS alert_rules (
  id TEXT PRIMARY KEY,
  org_id TEXT,
  name TEXT,
  description TEXT,
  metric TEXT,
  operator TEXT,
  threshold REAL,
  duration_seconds INTEGER,
  severity TEXT,
  enabled INTEGER,
  actions TEXT,
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS notification_channels (
  id TEXT PRIMARY KEY,
  org_id TEXT,
  type TEXT,
  name TEXT,
  config_encrypted TEXT,
  is_enabled INTEGER,
  is_default INTEGER,
  created_at TEXT
);

CREATE TABLE IF NOT EXISTS dashboards (
  id TEXT PRIMARY KEY,
  org_id TEXT,
  owner_id TEXT,
  name TEXT,
  description TEXT,
  category TEXT,
  tags TEXT,
  widgets TEXT,
  layout TEXT,
  refresh_interval INTEGER,
  is_public INTEGER,
  created_at TEXT,
  updated_at TEXT
);

CREATE TABLE IF NOT EXISTS integrations (
  id TEXT PRIMARY KEY,
  org_id TEXT,
  type TEXT,
  name TEXT,
  status TEXT,
  config_encrypted TEXT,
  last_sync TEXT,
  error TEXT
);

CREATE TABLE IF NOT EXISTS settings (
  org_id TEXT NOT NULL,
  key TEXT NOT NULL,
  value_encrypted TEXT,
  PRIMARY KEY (org_id, key)
);

CREATE TABLE IF NOT EXISTS agent_keys (
  id TEXT PRIMARY KEY,
  org_id TEXT,
  name TEXT,
  key_hash TEXT NOT NULL,
  created_at TEXT NOT NULL,
  last_seen TEXT
);

CREATE TABLE IF NOT EXISTS ip_allowlist (
  id TEXT PRIMARY KEY,
  org_id TEXT,
  cidr TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS oauth_states (
  state TEXT PRIMARY KEY,
  created_at TEXT NOT NULL,
  org_id TEXT,
  purpose TEXT
);

CREATE TABLE IF NOT EXISTS db_backups (
  id TEXT PRIMARY KEY,
  org_id TEXT,
  connection_id TEXT,
  created_at TEXT NOT NULL,
  note TEXT,
  file_path TEXT,
  size_bytes INTEGER,
  kind TEXT
);

CREATE TABLE IF NOT EXISTS invites (
  id TEXT PRIMARY KEY,
  org_id TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL,
  token_hash TEXT NOT NULL,
  invited_by TEXT,
  expires_at TEXT NOT NULL,
  accepted_at TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS password_resets (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  org_id TEXT NOT NULL,
  token_hash TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL
);
`;

const POSTGRES_SCHEMA = SQLITE_SCHEMA.replace(
  /INTEGER PRIMARY KEY AUTOINCREMENT/g,
  'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
);

class SqliteAdapter implements DbAdapter {
  kind = 'sqlite';
  private db: DatabaseSync;

  constructor(filePath: string) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    this.db = new DatabaseSync(filePath);
    this.db.exec('PRAGMA journal_mode = WAL;');
    this.db.exec('PRAGMA foreign_keys = ON;');
  }

  async exec(sql: string): Promise<void> {
    this.db.exec(sql);
  }

  async run(sql: string, params: SqlParams = []): Promise<void> {
    this.db.prepare(sql).run(...params);
  }

  async get<T = Record<string, unknown>>(sql: string, params: SqlParams = []): Promise<T | undefined> {
    return this.db.prepare(sql).get(...params) as T | undefined;
  }

  async all<T = Record<string, unknown>>(sql: string, params: SqlParams = []): Promise<T[]> {
    return this.db.prepare(sql).all(...params) as T[];
  }

  async close(): Promise<void> {
    this.db.close();
  }
}

function toPg(sql: string): string {
  let i = 0;
  return sql.replace(/\?/g, () => `$${++i}`);
}

class PostgresAdapter implements DbAdapter {
  kind = 'postgres';
  private pool: pg.Pool;

  constructor() {
    const Pool = pg.Pool || (pg as { default?: { Pool: typeof pg.Pool } }).default?.Pool;
    if (!Pool) throw new Error('pg Pool export missing');
    this.pool = new Pool({
      host: config.postgres.host,
      port: config.postgres.port,
      database: config.postgres.database,
      user: config.postgres.user,
      password: config.postgres.password,
      ssl: config.postgres.ssl ? { rejectUnauthorized: config.postgres.sslRejectUnauthorized } : undefined,
      max: 10,
    });
  }

  async exec(sql: string): Promise<void> {
    const statements = sql.split(';').map((s) => s.trim()).filter(Boolean);
    for (const statement of statements) {
      await this.pool.query(statement);
    }
  }

  async run(sql: string, params: SqlParams = []): Promise<void> {
    await this.pool.query(toPg(sql), params);
  }

  async get<T = Record<string, unknown>>(sql: string, params: SqlParams = []): Promise<T | undefined> {
    const res = await this.pool.query(toPg(sql), params);
    return res.rows[0] as T | undefined;
  }

  async all<T = Record<string, unknown>>(sql: string, params: SqlParams = []): Promise<T[]> {
    const res = await this.pool.query(toPg(sql), params);
    return res.rows as T[];
  }

  async close(): Promise<void> {
    await this.pool.end();
  }
}

let adapter: DbAdapter | null = null;
let ready: Promise<DbAdapter> | null = null;

function sqliteFile(): string {
  return process.env.SQLITE_PATH || config.sqlitePath;
}

async function tryAddColumn(db: DbAdapter, table: string, column: string, spec: string): Promise<void> {
  try {
    await db.exec(`ALTER TABLE ${table} ADD COLUMN ${column} ${spec}`);
  } catch {
    // column already exists
  }
}

async function migrateSqlite(db: DbAdapter): Promise<void> {
  const usersSql = await db.get<{ sql: string }>("SELECT sql FROM sqlite_master WHERE type='table' AND name='users'");
  if (usersSql?.sql?.includes('username TEXT UNIQUE')) {
    await db.exec(`
      CREATE TABLE IF NOT EXISTS users_migrated (
        id TEXT PRIMARY KEY,
        org_id TEXT NOT NULL,
        username TEXT NOT NULL,
        email TEXT NOT NULL,
        full_name TEXT,
        role TEXT NOT NULL,
        permissions TEXT NOT NULL,
        password_hash TEXT NOT NULL,
        is_active INTEGER NOT NULL DEFAULT 1,
        failed_login_attempts INTEGER NOT NULL DEFAULT 0,
        locked_until TEXT,
        last_login TEXT,
        totp_secret TEXT,
        totp_enabled INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        UNIQUE(org_id, username)
      );
      INSERT OR IGNORE INTO users_migrated (id, org_id, username, email, full_name, role, permissions, password_hash, is_active, failed_login_attempts, locked_until, last_login, created_at, updated_at)
      SELECT id, org_id, username, email, full_name, role, permissions, password_hash, is_active, failed_login_attempts, locked_until, last_login, created_at, updated_at FROM users;
      DROP TABLE users;
      ALTER TABLE users_migrated RENAME TO users;
    `);
  }
  const settingsSql = await db.get<{ sql: string }>("SELECT sql FROM sqlite_master WHERE type='table' AND name='settings'");
  if (settingsSql?.sql?.includes('key TEXT PRIMARY KEY')) {
    await db.exec(`
      CREATE TABLE IF NOT EXISTS settings_migrated (
        org_id TEXT NOT NULL,
        key TEXT NOT NULL,
        value_encrypted TEXT,
        PRIMARY KEY (org_id, key)
      );
      INSERT OR IGNORE INTO settings_migrated (org_id, key, value_encrypted)
      SELECT COALESCE(org_id, 'legacy'), key, value_encrypted FROM settings;
      DROP TABLE settings;
      ALTER TABLE settings_migrated RENAME TO settings;
    `);
  }
  await tryAddColumn(db, 'users', 'totp_secret', 'TEXT');
  await tryAddColumn(db, 'users', 'totp_enabled', 'INTEGER NOT NULL DEFAULT 0');
  await tryAddColumn(db, 'oauth_states', 'org_id', 'TEXT');
  await tryAddColumn(db, 'oauth_states', 'purpose', 'TEXT');
  await tryAddColumn(db, 'db_backups', 'file_path', 'TEXT');
  await tryAddColumn(db, 'db_backups', 'size_bytes', 'INTEGER');
  await tryAddColumn(db, 'db_backups', 'kind', 'TEXT');
}

export async function initDb(): Promise<DbAdapter> {
  if (adapter) return adapter;
  if (ready) return ready;
  ready = (async () => {
    const type = (process.env.DATABASE_TYPE || config.databaseType || 'sqlite').toLowerCase();
    if (type === 'postgres' || type === 'postgresql') {
      adapter = new PostgresAdapter();
      await adapter.exec(POSTGRES_SCHEMA);
    } else {
      adapter = new SqliteAdapter(sqliteFile());
      await adapter.exec(SQLITE_SCHEMA);
      await migrateSqlite(adapter);
    }
    return adapter;
  })();
  return ready;
}

export function getDb(): DbAdapter {
  if (!adapter) {
    throw new Error('Database is not initialized. Call initDb() first.');
  }
  return adapter;
}

export async function closeDb(): Promise<void> {
  await adapter?.close();
  adapter = null;
  ready = null;
}

export function nowIso(): string {
  return new Date().toISOString();
}

export function parseJson<T>(raw: string | null | undefined, fallback: T): T {
  if (!raw) return fallback;
  try {
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}
